spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true
logging:
  level:
    academy.devdojo: debug #package name
server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20